version: '3'
services:
  db:
    image : cleverinjection
    ports : [3399:80]
    build:
      context: .
      dockerfile: dockerfile
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
